"""Small async PostgreSQL adapter for the existing SQL client.

The application keeps SQLite for local development and tests, while production
uses Neon through DATABASE_URL. This adapter intentionally mirrors the tiny
aiosqlite surface used by SQLClient so the domain queries stay shared.
"""

from __future__ import annotations

import inspect
import re
from typing import Any

import psycopg
from psycopg import AsyncConnection
from psycopg.rows import tuple_row

import aiosqlite


_PLACEHOLDER = re.compile(r"\?")
_NOCASE = re.compile(r"\s+COLLATE\s+NOCASE", re.IGNORECASE)
_AUTOINCREMENT = re.compile(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE)
_IGNORE_INSERT = re.compile(r"INSERT\s+OR\s+IGNORE\s+INTO", re.IGNORECASE)
_PRAGMA_COLUMNS = re.compile(r"^\s*PRAGMA\s+table_info\(([^)]+)\)\s*$", re.IGNORECASE)
_RETENTION_DATE = re.compile(
    r"(\w+)\s*<\s*datetime\('now',\s*%s\)", re.IGNORECASE
)
_TEXT_TIMESTAMP_COMPARISON = re.compile(
    r"\b(expires_at|deletion_scheduled_for|created_at)\s*(<=|>=|<|>)\s*CURRENT_TIMESTAMP\b",
    re.IGNORECASE,
)


def _translate_sql(sql: str) -> str:
    sql = sql.strip()
    if sql.upper().startswith("PRAGMA"):
        return sql
    ignore_insert = bool(_IGNORE_INSERT.search(sql))
    sql = sql.replace("BEGIN IMMEDIATE", "BEGIN")
    sql = _NOCASE.sub("", sql)
    sql = _AUTOINCREMENT.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    sql = _IGNORE_INSERT.sub("INSERT INTO", sql)
    sql = _PLACEHOLDER.sub("%s", sql)
    sql = _RETENTION_DATE.sub(
        r"\1::timestamp < (CURRENT_TIMESTAMP + %s::interval)", sql
    )
    sql = _TEXT_TIMESTAMP_COMPARISON.sub(r"\1::timestamp \2 CURRENT_TIMESTAMP", sql)
    if ignore_insert and "ON CONFLICT" not in sql.upper():
        if " RETURNING " in sql.upper():
            sql = re.sub(
                r"\s+RETURNING\s+",
                " ON CONFLICT DO NOTHING RETURNING ",
                sql,
                count=1,
                flags=re.IGNORECASE,
            )
        else:
            sql += " ON CONFLICT DO NOTHING"
    return sql


class PostgresConnection:
    def __init__(self, connection: AsyncConnection[Any] | Any):
        self._connection = connection

    async def __aenter__(self) -> PostgresConnection:
        if inspect.isawaitable(self._connection):
            self._connection = await self._connection
        await self._connection.__aenter__()
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self._connection.__aexit__(exc_type, exc, tb)

    async def execute(self, sql: str, params: Any = ()):
        pragma_columns = _PRAGMA_COLUMNS.match(sql)
        if pragma_columns:
            table = pragma_columns.group(1).strip().strip('"')
            return await self._connection.execute(
                "SELECT ordinal_position - 1, column_name "
                "FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = %s "
                "ORDER BY ordinal_position",
                (table,),
            )
        if sql.strip().upper().startswith("PRAGMA"):
            return _NoopCursor()
        try:
            return await self._connection.execute(_translate_sql(sql), params)
        except psycopg.errors.UniqueViolation as exc:
            raise aiosqlite.IntegrityError(str(exc)) from exc
        except psycopg.errors.ForeignKeyViolation as exc:
            raise aiosqlite.IntegrityError(str(exc)) from exc

    async def commit(self) -> None:
        await self._connection.commit()

    async def rollback(self) -> None:
        await self._connection.rollback()


class _NoopCursor:
    rowcount = 0

    async def fetchone(self):
        return None

    async def fetchall(self):
        return []


def connect(database_url: str) -> PostgresConnection:
    return PostgresConnection(
        psycopg.AsyncConnection.connect(database_url, row_factory=tuple_row)
    )


async def table_columns(database_url: str, table: str) -> set[str]:
    async with connect(database_url) as db:
        cursor = await db.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = %s ORDER BY ordinal_position",
            (table,),
        )
        return {row[0] for row in await cursor.fetchall()}
